### ISSUE TITLE
Question about the training time

### ISSUE THREAD

**Issue by fyabc** [wasiahmad/NeuralCodeSum#10]
Hello, I am running the code to reproduce the results in the paper.
I train the Java baseline model on **4** Tesla P40 GPU cards, and all hyperparameters remain unchanged.
The model takes **2.5 days** to train for 200 epochs (~20min per epoch).
Is this training time in expectation? Can you provide some information about the training time of baseline models?

Thanks!

**Comment by wasiahmad** [comment]
Hi,

We ran the model on **2 GeForce RTX 2080 (11gb)** and it took ~15 mins (1 epoch training) and ~3 mins (1 epoch validation), total ~18 mins for an epoch. And the total training time was around ~60 hours.

I am curious, why do you need 4 GPUs? P40 GPUs have 24GB of memory, right?

**Comment by fyabc** [comment]
Thank you for your reply.

> I am curious, why do you need 4 GPUs? P40 GPUs have 24GB of memory, right?
Yes, P40 GPUs have 24GB of memory. I just want to use more GPUs to speed up the training, but it seems that training on 4 GPUs is not faster than 2 GPUs. I will rerun the model on 2 GPUs.
