### ISSUE TITLE
problem during reproducing

### ISSUE THREAD

**Issue by 3-sung** [wasiahmad/NeuralCodeSum#14]
Thank you for your good model and research.

I trained rnn model and TRANSFORMER model. 

However, i got a error message when testing both model epoch 0.

The error message is 
""""
Traceback (most recent call last):
  File "../../main/train.py", line 704, in <module>
    main(args)
  File "../../main/train.py", line 627, in main
    validate_official(args, dev_loader, model, stats, mode='test')
  File "../../main/train.py", line 345, in validate_official
    mode=mode)
  File "../../main/train.py", line 442, in eval_accuracies
    meteor, _ = meteor_calculator.compute_score(references, hypotheses)
  File "/content/gdrive/My Drive/Transformer/NeuralCodeSum-master/c2nl/eval/meteor/meteor.py", line 76, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/content/gdrive/My Drive/Transformer/NeuralCodeSum-master/c2nl/eval/meteor/meteor.py", line 106, in _stat
    self.meteor_p.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe 
""""
Please suggest the cause or solution of the problem.

Take care of your health and thank you for reading !

"""
My Environment
google colab(Ubuntu 18.04.5 LTS)
python 3.6.9
"""

**Comment by wasiahmad** [comment]
Hi, the problem looks related to METEOR computation which is perhaps related to the related package installation. I would suggest to turn everything off related to METEOR calculation and see if the program runs fine in your environment. You may compute METEOR locally later on, on the generated summaries! 

One alternative is to use the METEOR from the NLTK library (https://www.nltk.org/_modules/nltk/translate/meteor_score.html).

**Comment by 3-sung** [comment]
Thank for your answer. 

It worked. However, I wonder how to set the parameter (alpha, beta, gamma) in the process of calculating the meter score locally by NLTK library which you recommend.

Thank you for reading!
