### ISSUE TITLE
program did not create .mdl files in tmp directory

### ISSUE THREAD

**Issue by Zinper** [wasiahmad/NeuralCodeSum#17]
i follow your instruction to run the bash files,but it did not create the tmp files as you listed.the bash file did not creat the .mdl files. is there any solution?

**Comment by Zinper** [comment]
ps. i train in the python transformer.sh

**Comment by wasiahmad** [comment]
The problem description does not provide enough information so that I can help you. Follow the instructions carefully, it should work. The code is verified by others.
