### ISSUE TITLE
Error on the file generation

### ISSUE THREAD

**Issue by MatteoZhang** [wasiahmad/NeuralCodeSum#18]
Hi, I am a master student venturing in the code summarization field, 
I wanted to try the code using this command: **bash generate.sh 0 code2jdoc sample.code**
but an OSError araised:
_Traceback (most recent call last):
  File "../main/test.py", line 474, in <module>
    main(args)
  File "../main/test.py", line 400, in main
    raise IOError('No such file: %s' % args.model_file)
OSError: No such file: ../tmp/code2jdoc.mdl_

**Comment by wasiahmad** [comment]
Hi, please read the readme file carefully. You need to train the model first which will produce `code2jdoc.mdl` file inside the `tmp` directory. Then you can perform generation.
