### ISSUE TITLE
Some of the problems

### ISSUE THREAD

**Issue by Zhangxq-1** [wasiahmad/NeuralCodeSum#2]
Dear Professor ,thank you for reading! When I run the code following the steps, I meet some problems.Can you help me ?
the problems is:
OSError:No such file"  /home/zxq/code/NeuralCodeSum/data/java/train/code.origin_subtoken
and when I run the bash get_data.sh,
I got: FileNotFoundError: no such file or directory : 'train/code.original_subtoken

now I am solving this problem by downloading the dataset Manually

**Comment by wasiahmad** [comment]
Hi, I am unable to reproduce the error that you reported. On my side, the codebase in the current repository works fine. Can you clone the repo from latent commit and try one more time?

**Comment by Zhangxq-1** [comment]
ok, now I am solving this problem by downloading the dataset manually.Thank you very  much

**Comment by Zhangxq-1** [comment]
Hi , I am process the  code.original to  code.original_subtoken, it will be great if you can provide me with the source code, I am doing some other experiments on it.

**Comment by Guardian99** [comment]
How to generate a summary on a given file using the trained model?

**Comment by wasiahmad** [comment]
Please checkout the bash [scripts](https://github.com/wasiahmad/NeuralCodeSum/tree/master/scripts). You can either run the greedy test or beam search test (or both too) by placing the trained model in the appropriate location.

**Comment by Guardian99** [comment]
Given a piece of code, how do i create subtokens for it in order to augment the dataset?

**Comment by wasiahmad** [comment]
> Given a piece of code, how do I create subtokens for it in order to augment the dataset?

Please see the [code_tokenizer](https://github.com/wasiahmad/NeuralCodeSum/blob/master/c2nl/tokenizers/code_tokenizer.py) to see how we performed sub-tokenization.
