### ISSUE TITLE
code.original_subtoken file not found

### ISSUE THREAD

**Issue by krshubh** [wasiahmad/NeuralCodeSum#22]
when I am training or evaluating, getting an error

> OSError: No such file: ../../data/python/test/code.original_subtoken

Please suggest where could I find those folder data/python/test and data/python/train.

**Comment by wasiahmad** [comment]
All the code released is tested, so if you face any error at your end (especially the type of error you faced), it means you didn't go through the documentation carefully. We do not want to help someone who doesn't help himself/herself. Please help yourself by reading the documentation carefully.
