### ISSUE TITLE
RuntimeError: "index_select_out_cuda_impl" not implemented for 'Float While comment generation testing the code

### ISSUE THREAD

**Issue by sawan16** [wasiahmad/NeuralCodeSum#26]
============Generating (Beam)============
05/02/2021 10:06:46 AM: [ COMMAND: ../main/test.py --only_generate True --data_workers 5 --dataset_name java --data_dir ../data/ --model_dir ../tmp --model_name code2jdoc --dev_src sample.code --uncase True --max_examples -1 --max_src_len 150 --max_tgt_len 50 --test_batch_size 64 --beam_size 4 --n_best 1 --block_ngram_repeat 3 --stepwise_penalty False --coverage_penalty none --length_penalty none --beta 0 --gamma 0 --replace_unk ]
05/02/2021 10:06:46 AM: [ ---------------------------------------------------------------------------------------------------- ]
05/02/2021 10:06:46 AM: [ Load and process data files ]
100% 20/20 [00:00<00:00, 76538.39it/s]
100% 20/20 [00:00<00:00, 12735.10it/s]
05/02/2021 10:06:46 AM: [ Num dev examples = 20 ]
05/02/2021 10:06:46 AM: [ ---------------------------------------------------------------------------------------------------- ]
05/02/2021 10:06:46 AM: [ Loading model ../tmp/code2jdoc.mdl ]
05/02/2021 10:06:51 AM: [ ---------------------------------------------------------------------------------------------------- ]
05/02/2021 10:06:51 AM: [ Make data loaders ]
05/02/2021 10:06:51 AM: [ ---------------------------------------------------------------------------------------------------- ]
05/02/2021 10:06:51 AM: [ CONFIG:
{
    "attn_type": "general",
    "beam_size": 4,
    "beta": 0.0,
    "bidirection": true,
    "block_ngram_repeat": 3,
    "char_emsize": 16,
    "code_tag_type": "subtoken",
    "conditional_decoding": false,
    "copy_attn": false,
    "coverage_attn": false,
    "coverage_penalty": "none",
    "cuda": true,
    "d_ff": 2048,
    "d_k": 64,
    "d_v": 64,
    "data_dir": "../data/",
    "data_workers": 5,
    "dataset_name": [
        "java"
    ],
    "dev_src": [
        "sample.code"
    ],
    "dev_src_files": [
        "../data/java/sample.code"
    ],
    "dev_src_tag": null,
    "dev_src_tag_files": [
        null
    ],
    "dev_tgt": null,
    "dev_tgt_files": [
        null
    ],
    "dropout": 0.2,
    "dropout_emb": 0.2,
    "dropout_rnn": 0.2,
    "early_stop": 5,
    "emsize": 300,
    "filter_size": 5,
    "fix_embeddings": true,
    "force_copy": false,
    "gamma": 0.0,
    "grad_clipping": 5.0,
    "ignore_when_blocking": [],
    "layer_wise_attn": false,
    "learning_rate": 0.001,
    "length_penalty": "none",
    "log_file": "../tmp/code2jdoc_beam.txt",
    "lr_decay": 0.99,
    "max_characters_per_token": 30,
    "max_examples": -1,
    "max_relative_pos": 0,
    "max_src_len": 150,
    "max_tgt_len": 50,
    "model_dir": "../tmp",
    "model_file": "../tmp/code2jdoc.mdl",
    "model_name": "code2jdoc",
    "model_type": "rnn",
    "momentum": 0,
    "n_best": 1,
    "n_characters": 260,
    "nfilters": 100,
    "nhid": 200,
    "nlayers": 2,
    "num_head": 8,
    "only_generate": true,
    "optimizer": "adam",
    "parallel": false,
    "pred_file": "../tmp/code2jdoc_beam.json",
    "random_seed": 1013,
    "reload_decoder_state": null,
    "replace_unk": true,
    "reuse_copy_attn": false,
    "review_attn": false,
    "rnn_type": "LSTM",
    "share_decoder_embeddings": false,
    "sort_by_len": true,
    "split_decoder": false,
    "src_pos_emb": true,
    "stepwise_penalty": false,
    "test_batch_size": 64,
    "tgt_pos_emb": true,
    "trans_drop": 0.2,
    "uncase": true,
    "use_all_enc_layers": false,
    "use_code_type": false,
    "use_neg_dist": true,
    "use_src_char": false,
    "use_src_word": true,
    "use_tgt_char": false,
    "use_tgt_word": true,
    "verbose": false,
    "warmup_epochs": 0,
    "warmup_steps": 10000,
    "weight_decay": 0
} ]
  0% 0/1 [00:00<?, ?it/s]**tensor([0.7018, 0.7952, 0.4606, 0.9982], device='cuda:0')**
Traceback (most recent call last):
  File "../main/test.py", line 474, in <module>
    main(args)
  File "../main/test.py", line 436, in main
    validate_official(args, dev_loader, model)
  File "../main/test.py", line 280, in validate_official
    ret = translator.translate_batch(batch_inputs)
  File "/content/drive/My Drive/notebooks/class_doc_gen/class_comment_gen/method_doc_gen/transformer_based_work/NeuralCodeSum/c2nl/translator/translator.py", line 242, in translate_batch
    beam_attn.data[:, j, :memory_lengths[j]])
  File "/content/drive/My Drive/notebooks/class_doc_gen/class_comment_gen/method_doc_gen/transformer_based_work/NeuralCodeSum/c2nl/translator/beam.py", line 135, in advance
    ttt = attn_out.index_select(0, prev_k)
**RuntimeError: "index_select_out_cuda_impl" not implemented for 'Float'**
  0% 0/1 [00:00<?, ?it/s]

**Comment by wasiahmad** [comment]
Please check the required version of the software needed.

**Comment by DRMALEK** [comment]
Uninstalling the current version of PyTorch, and installing 1.3.0 version worked for me. 
I assume there is a bug in the requriements.txt file tough.

**Comment by Doragd** [comment]
I met the same issue. This problem is caused by how division is treated in different versions of PyTorch (`beam.py line:131` `prevK = bestScoresId / numWords`). You can modify this line to `prevK = bestScoresId // numWords`
