### ISSUE TITLE
Generating summary for a file.

### ISSUE THREAD

**Issue by Guardian99** [wasiahmad/NeuralCodeSum#3]
After training, i have the tmp dir but how do i test the trained model on a single file?

**Comment by wasiahmad** [comment]
If you are using the scripts provided by us, then it should perform the testing right after training. Please check the bash scripts. For example, check the [transformer.sh](https://github.com/wasiahmad/NeuralCodeSum/blob/master/scripts/java/transformer.sh#L143) script for the Java dataset.

**Comment by Guardian99** [comment]
But i want to see the output on a single file. How do i do that?

**Comment by Zhangxq-1** [comment]
i have the same problem with you. i think we should rewrite the test file

**Comment by wasiahmad** [comment]
> But i want to see the output on a single file. How do i do that?

What do you mean by that? The generated summaries are written in a JSON file. Did you read this [section](https://github.com/wasiahmad/NeuralCodeSum#generated-log-files) from README?

**Comment by Guardian99** [comment]
Here is what i am looking for. After running the bash transformer.sh 0,1 code2jdoc, I have the files generated in the tmp directory with all the names mentioned in the README file.
Now here is what i want. I have a java doc for which i want a summary. Since i have already trained the model and the files mentioned in README, how do i use these files to generate the summary for this single file that I want a summary of.

**Comment by wasiahmad** [comment]
I cited the bash scripts before to see how we perform the test. For example, this is the function that we use to perform test using the transformer model.

```
function test () {

echo "============TESTING============"

RGPU=$1
MODEL_NAME=$2

PYTHONPATH=$SRC_DIR CUDA_VISIBLE_DEVICES=$RGPU python -W ignore ${SRC_DIR}/main/train.py \
--only_test True \
--data_workers 5 \
--dataset_name $DATASET \
--data_dir ${DATA_DIR}/ \
--model_dir $MODEL_DIR \
--model_name $MODEL_NAME \
--dev_src test/code.${CODE_EXTENSION} \
--dev_src_tag test/code.${CODE_EXTENSION} \
--dev_tgt test/javadoc.${JAVADOC_EXTENSION} \
--code_tag_type $CODE_EXTENSION \
--use_code_type False \
--uncase True \
--max_src_len 150 \
--max_tgt_len 50 \
--max_examples -1 \
--test_batch_size 64

}
```

Here, you need to note the flags: `dev_src`, `dev_src_tag`, and `dev_tgt`. It is important to note that, our codebase expects that you have the target summary to compute the evaluation metric values. 

If you only want to generate summaries without performing an evaluation, you need to modify the code, which would be very easy. I will try to add provision so that a summary can be generated without performing an evaluation. Hopefully, in a week!

**Comment by anshul17024** [comment]
Hi, I am having the same problem. I also want to generate the summary instead of evaluating it. Do I need to generate the subtokens as well or a direct paste in a test directory would give the summary. Or if you can in short tell where do I need to make the changes?

**Comment by anshul17024** [comment]
And can you also please tell how have you generated subtoken files?

**Comment by wasiahmad** [comment]
Finally, the wait is over. I have updated the codebase. Please read this [section](https://github.com/wasiahmad/NeuralCodeSum#generating-summaries-for-source-codes) to generate summaries from a source code input file.

**Comment by wasiahmad** [comment]
> And can you also please tell how have you generated subtoken files?

Please see the [code_tokenizer](https://github.com/wasiahmad/NeuralCodeSum/blob/master/c2nl/tokenizers/code_tokenizer.py) to see how we performed sub-tokenization.

**Comment by anshul17024** [comment]
Thank you so so much, sir.

**Comment by anshul17024** [comment]
Thank you so so much, sir. I tried the instructions which you have written today, I have put code2jdoc_beam.txt, code2jdoc.mdl, code2jdoc.json, code2jdoc_test.txt files in the tmp folder. When entering the command **bash generate.sh 0 code2jdoc sample.code**, I am getting the following error: 
`============Generating (Beam)============
06/16/2020 05:10:35 PM: [ COMMAND: ../main/test.py --only_generate True --data_workers 5 --dataset_name java --data_dir ../data/ --model_dir ../tmp --model_name code2jdoc --dev_src sample.code --uncase True --max_examples -1 --max_src_len 150 --max_tgt_len 50 --test_batch_size 64 --beam_size 4 --n_best 1 --block_ngram_repeat 3 --stepwise_penalty False --coverage_penalty none --length_penalty none --beta 0 --gamma 0 --replace_unk ]
06/16/2020 05:10:35 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:35 PM: [ Load and process data files ]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 231572.84it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 51580.10it/s]
06/16/2020 05:10:35 PM: [ Num dev examples = 98 ]
06/16/2020 05:10:35 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:35 PM: [ Loading model ../tmp/code2jdoc.mdl ]
06/16/2020 05:10:38 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:38 PM: [ Make data loaders ]
06/16/2020 05:10:38 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:38 PM: [ CONFIG:
{
    "attn_type": "general",
    "beam_size": 4,
    "beta": 0.0,
    "bidirection": true,
    "block_ngram_repeat": 3,
    "char_emsize": 16,
    "code_tag_type": "subtoken",
    "conditional_decoding": false,
    "copy_attn": false,
    "coverage_attn": false,
    "coverage_penalty": "none",
    "cuda": false,
    "d_ff": 2048,
    "d_k": 64,
    "d_v": 64,
    "data_dir": "../data/",
    "data_workers": 5,
    "dataset_name": [
        "java"
    ],
    "dev_src": [
        "sample.code"
    ],
    "dev_src_files": [
        "../data/java/sample.code"
    ],
    "dev_src_tag": null,
    "dev_src_tag_files": [
        null
    ],
    "dev_tgt": null,
    "dev_tgt_files": [
        null
    ],
    "dropout": 0.2,
    "dropout_emb": 0.2,
    "dropout_rnn": 0.2,
    "early_stop": 5,
    "emsize": 300,
    "filter_size": 5,
    "fix_embeddings": true,
    "force_copy": false,
    "gamma": 0.0,
    "grad_clipping": 5.0,
    "ignore_when_blocking": [],
    "layer_wise_attn": false,
    "learning_rate": 0.001,
    "length_penalty": "none",
    "log_file": "../tmp/code2jdoc_beam.txt",
    "lr_decay": 0.99,
    "max_characters_per_token": 30,
    "max_examples": -1,
    "max_relative_pos": 0,
    "max_src_len": 150,
    "max_tgt_len": 50,
    "model_dir": "../tmp",
    "model_file": "../tmp/code2jdoc.mdl",
    "model_name": "code2jdoc",
    "model_type": "rnn",
    "momentum": 0,
    "n_best": 1,
    "n_characters": 260,
    "nfilters": 100,
    "nhid": 200,
    "nlayers": 2,
    "num_head": 8,
    "only_generate": true,
    "optimizer": "adam",
    "parallel": false,
    "pred_file": "../tmp/code2jdoc_beam.json",
    "random_seed": 1013,
    "reload_decoder_state": null,
    "replace_unk": true,
    "reuse_copy_attn": false,
    "review_attn": false,
    "rnn_type": "LSTM",
    "share_decoder_embeddings": false,
    "sort_by_len": true,
    "split_decoder": false,
    "src_pos_emb": true,
    "stepwise_penalty": false,
    "test_batch_size": 64,
    "tgt_pos_emb": true,
    "trans_drop": 0.2,
    "uncase": true,
    "use_all_enc_layers": false,
    "use_code_type": false,
    "use_neg_dist": true,
    "use_src_char": false,
    "use_src_word": true,
    "use_tgt_char": false,
    "use_tgt_word": true,
    "verbose": false,
    "warmup_epochs": 0,
    "warmup_steps": 10000,
    "weight_decay": 0
} ]
  0%|                                                                                                                   | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "../main/test.py", line 474, in <module>
    main(args)
  File "../main/test.py", line 436, in main
    validate_official(args, dev_loader, model)
  File "../main/test.py", line 278, in validate_official
    batch_inputs = prepare_batch(ex, model)
  File "../main/test.py", line 216, in prepare_batch
    source_map = make_src_map(batch['src_map'])
  File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/utils/copy_utils.py", line 34, in make_src_map
    src_vocab_size = max([t.max() for t in data]) + 1
  File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/utils/copy_utils.py", line 34, in <listcomp>
    src_vocab_size = max([t.max() for t in data]) + 1
RuntimeError: operation does not have an identity.
  0%|                                                                                                                   | 0/2 [00:00<?, ?it/s]`
Can you please tell how can I resolve this?
Also, can you please tell how to run the tokenizer files, as there are 3 different files which you have uploaded, and none of them takes any input. It will be really helpful, sir.

**Comment by anshul17024** [comment]
Thank you so so much, sir. I tried the instructions which you have written today, I have put code2jdoc_beam.txt, code2jdoc.mdl, code2jdoc.json, code2jdoc_test.txt files in the tmp folder. When entering the command bash generate.sh 0 code2jdoc sample.code, I am getting the following error:

`============Generating (Beam)============
06/16/2020 05:10:35 PM: [ COMMAND: ../main/test.py --only_generate True --data_workers 5 --dataset_name java --data_dir ../data/ --model_dir ../tmp --model_name code2jdoc --dev_src sample.code --uncase True --max_examples -1 --max_src_len 150 --max_tgt_len 50 --test_batch_size 64 --beam_size 4 --n_best 1 --block_ngram_repeat 3 --stepwise_penalty False --coverage_penalty none --length_penalty none --beta 0 --gamma 0 --replace_unk ]
06/16/2020 05:10:35 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:35 PM: [ Load and process data files ]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 231572.84it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 51580.10it/s]
06/16/2020 05:10:35 PM: [ Num dev examples = 98 ]
06/16/2020 05:10:35 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:35 PM: [ Loading model ../tmp/code2jdoc.mdl ]
06/16/2020 05:10:38 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:38 PM: [ Make data loaders ]
06/16/2020 05:10:38 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:38 PM: [ CONFIG:
{
    "attn_type": "general",
    "beam_size": 4,
    "beta": 0.0,
    "bidirection": true,
    "block_ngram_repeat": 3,
    "char_emsize": 16,
    "code_tag_type": "subtoken",
    "conditional_decoding": false,
    "copy_attn": false,
    "coverage_attn": false,
    "coverage_penalty": "none",
    "cuda": false,
    "d_ff": 2048,
    "d_k": 64,
    "d_v": 64,
    "data_dir": "../data/",
    "data_workers": 5,
    "dataset_name": [
        "java"
    ],
    "dev_src": [
        "sample.code"
    ],
    "dev_src_files": [
        "../data/java/sample.code"
    ],
    "dev_src_tag": null,
    "dev_src_tag_files": [
        null
    ],
    "dev_tgt": null,
    "dev_tgt_files": [
        null
    ],
    "dropout": 0.2,
    "dropout_emb": 0.2,
    "dropout_rnn": 0.2,
    "early_stop": 5,
    "emsize": 300,
    "filter_size": 5,
    "fix_embeddings": true,
    "force_copy": false,
    "gamma": 0.0,
    "grad_clipping": 5.0,
    "ignore_when_blocking": [],
    "layer_wise_attn": false,
    "learning_rate": 0.001,
    "length_penalty": "none",
    "log_file": "../tmp/code2jdoc_beam.txt",
    "lr_decay": 0.99,
    "max_characters_per_token": 30,
    "max_examples": -1,
    "max_relative_pos": 0,
    "max_src_len": 150,
    "max_tgt_len": 50,
    "model_dir": "../tmp",
    "model_file": "../tmp/code2jdoc.mdl",
    "model_name": "code2jdoc",
    "model_type": "rnn",
    "momentum": 0,
    "n_best": 1,
    "n_characters": 260,
    "nfilters": 100,
    "nhid": 200,
    "nlayers": 2,
    "num_head": 8,
    "only_generate": true,
    "optimizer": "adam",
    "parallel": false,
    "pred_file": "../tmp/code2jdoc_beam.json",
    "random_seed": 1013,
    "reload_decoder_state": null,
    "replace_unk": true,
    "reuse_copy_attn": false,
    "review_attn": false,
    "rnn_type": "LSTM",
    "share_decoder_embeddings": false,
    "sort_by_len": true,
    "split_decoder": false,
    "src_pos_emb": true,
    "stepwise_penalty": false,
    "test_batch_size": 64,
    "tgt_pos_emb": true,
    "trans_drop": 0.2,
    "uncase": true,
    "use_all_enc_layers": false,
    "use_code_type": false,
    "use_neg_dist": true,
    "use_src_char": false,
    "use_src_word": true,
    "use_tgt_char": false,
    "use_tgt_word": true,
    "verbose": false,
    "warmup_epochs": 0,
    "warmup_steps": 10000,
    "weight_decay": 0
} ]
  0%|                                                                                                                   | 0/2 [00:00<?, ?it/s]

Traceback (most recent call last):
  File "../main/test.py", line 474, in <module>
    main(args)

  File "../main/test.py", line 436, in main
    validate_official(args, dev_loader, model)

  File "../main/test.py", line 278, in validate_official
    batch_inputs = prepare_batch(ex, model)

  File "../main/test.py", line 216, in prepare_batch
    source_map = make_src_map(batch['src_map'])

  File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/utils/copy_utils.py", line 34, in make_src_map

    src_vocab_size = max([t.max() for t in data]) + 1

  File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/utils/copy_utils.py", line 34, in <listcomp>

    src_vocab_size = max([t.max() for t in data]) + 1

RuntimeError: operation does not have an identity.

  0%|                                                                                                                   | 0/2 [00:00<?, ?it/s]`
Can you please tell how can I resolve this?
Also, can you please tell how to run the tokenizer files, as there are 3 different files which you have uploaded, and none of them takes any input. It will be really helpful, sir.

**Comment by anshul17024** [comment]
Thank you so so much, sir. I tried the instructions which you have written today, I have put code2jdoc_beam.txt, code2jdoc.mdl, code2jdoc.json, code2jdoc_test.txt files in the tmp folder. When entering the command bash generate.sh 0 code2jdoc sample.code, I am getting the following error:

`============Generating (Beam)============
06/16/2020 05:10:35 PM: [ COMMAND: ../main/test.py --only_generate True --data_workers 5 --dataset_name java --data_dir ../data/ --model_dir ../tmp --model_name code2jdoc --dev_src sample.code --uncase True --max_examples -1 --max_src_len 150 --max_tgt_len 50 --test_batch_size 64 --beam_size 4 --n_best 1 --block_ngram_repeat 3 --stepwise_penalty False --coverage_penalty none --length_penalty none --beta 0 --gamma 0 --replace_unk ]
06/16/2020 05:10:35 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:35 PM: [ Load and process data files ]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 231572.84it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 51580.10it/s]
06/16/2020 05:10:35 PM: [ Num dev examples = 98 ]
06/16/2020 05:10:35 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:35 PM: [ Loading model ../tmp/code2jdoc.mdl ]
06/16/2020 05:10:38 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:38 PM: [ Make data loaders ]
06/16/2020 05:10:38 PM: [ ---------------------------------------------------------------------------------------------------- ]
06/16/2020 05:10:38 PM: [ CONFIG:
{
"attn_type": "general",
"beam_size": 4,
"beta": 0.0,
"bidirection": true,
"block_ngram_repeat": 3,
"char_emsize": 16,
"code_tag_type": "subtoken",
"conditional_decoding": false,
"copy_attn": false,
"coverage_attn": false,
"coverage_penalty": "none",
"cuda": false,
"d_ff": 2048,
"d_k": 64,
"d_v": 64,
"data_dir": "../data/",
"data_workers": 5,
"dataset_name": [
"java"
],
"dev_src": [
"sample.code"
],
"dev_src_files": [
"../data/java/sample.code"
],
"dev_src_tag": null,
"dev_src_tag_files": [
null
],
"dev_tgt": null,
"dev_tgt_files": [
null
],
"dropout": 0.2,
"dropout_emb": 0.2,
"dropout_rnn": 0.2,
"early_stop": 5,
"emsize": 300,
"filter_size": 5,
"fix_embeddings": true,
"force_copy": false,
"gamma": 0.0,
"grad_clipping": 5.0,
"ignore_when_blocking": [],
"layer_wise_attn": false,
"learning_rate": 0.001,
"length_penalty": "none",
"log_file": "../tmp/code2jdoc_beam.txt",
"lr_decay": 0.99,
"max_characters_per_token": 30,
"max_examples": -1,
"max_relative_pos": 0,
"max_src_len": 150,
"max_tgt_len": 50,
"model_dir": "../tmp",
"model_file": "../tmp/code2jdoc.mdl",
"model_name": "code2jdoc",
"model_type": "rnn",
"momentum": 0,
"n_best": 1,
"n_characters": 260,
"nfilters": 100,
"nhid": 200,
"nlayers": 2,
"num_head": 8,
"only_generate": true,
"optimizer": "adam",
"parallel": false,
"pred_file": "../tmp/code2jdoc_beam.json",
"random_seed": 1013,
"reload_decoder_state": null,
"replace_unk": true,
"reuse_copy_attn": false,
"review_attn": false,
"rnn_type": "LSTM",
"share_decoder_embeddings": false,
"sort_by_len": true,
"split_decoder": false,
"src_pos_emb": true,
"stepwise_penalty": false,
"test_batch_size": 64,
"tgt_pos_emb": true,
"trans_drop": 0.2,
"uncase": true,
"use_all_enc_layers": false,
"use_code_type": false,
"use_neg_dist": true,
"use_src_char": false,
"use_src_word": true,
"use_tgt_char": false,
"use_tgt_word": true,
"verbose": false,
"warmup_epochs": 0,
"warmup_steps": 10000,
"weight_decay": 0
} ]
0%| | 0/2 [00:00<?, ?it/s]

Traceback (most recent call last):
File "../main/test.py", line 474, in
main(args)

File "../main/test.py", line 436, in main
validate_official(args, dev_loader, model)

File "../main/test.py", line 278, in validate_official
batch_inputs = prepare_batch(ex, model)

File "../main/test.py", line 216, in prepare_batch
source_map = make_src_map(batch['src_map'])

File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/utils/copy_utils.py", line 34, in make_src_map

src_vocab_size = max([t.max() for t in data]) + 1
File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/utils/copy_utils.py", line 34, in

src_vocab_size = max([t.max() for t in data]) + 1
RuntimeError: operation does not have an identity.

0%| | 0/2 [00:00<?, ?it/s]`
Can you please tell how can I resolve this?
Also, can you please tell how to run the tokenizer files, as there are 3 different files which you have uploaded, and none of them takes any input. It will be really helpful, sir.

**Comment by Guardian99** [comment]
> Thank you so so much, sir. I tried the instructions which you have written today, I have put code2jdoc_beam.txt, code2jdoc.mdl, code2jdoc.json, code2jdoc_test.txt files in the tmp folder. When entering the command bash generate.sh 0 code2jdoc sample.code, I am getting the following error:
> 
> `============Generating (Beam)============
> 06/16/2020 05:10:35 PM: [ COMMAND: ../main/test.py --only_generate True --data_workers 5 --dataset_name java --data_dir ../data/ --model_dir ../tmp --model_name code2jdoc --dev_src sample.code --uncase True --max_examples -1 --max_src_len 150 --max_tgt_len 50 --test_batch_size 64 --beam_size 4 --n_best 1 --block_ngram_repeat 3 --stepwise_penalty False --coverage_penalty none --length_penalty none --beta 0 --gamma 0 --replace_unk ]
> 06/16/2020 05:10:35 PM: [ ---------------------------------------------------------------------------------------------------- ]
> 06/16/2020 05:10:35 PM: [ Load and process data files ]
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 231572.84it/s]
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 51580.10it/s]
> 06/16/2020 05:10:35 PM: [ Num dev examples = 98 ]
> 06/16/2020 05:10:35 PM: [ ---------------------------------------------------------------------------------------------------- ]
> 06/16/2020 05:10:35 PM: [ Loading model ../tmp/code2jdoc.mdl ]
> 06/16/2020 05:10:38 PM: [ ---------------------------------------------------------------------------------------------------- ]
> 06/16/2020 05:10:38 PM: [ Make data loaders ]
> 06/16/2020 05:10:38 PM: [ ---------------------------------------------------------------------------------------------------- ]
> 06/16/2020 05:10:38 PM: [ CONFIG:
> {
> "attn_type": "general",
> "beam_size": 4,
> "beta": 0.0,
> "bidirection": true,
> "block_ngram_repeat": 3,
> "char_emsize": 16,
> "code_tag_type": "subtoken",
> "conditional_decoding": false,
> "copy_attn": false,
> "coverage_attn": false,
> "coverage_penalty": "none",
> "cuda": false,
> "d_ff": 2048,
> "d_k": 64,
> "d_v": 64,
> "data_dir": "../data/",
> "data_workers": 5,
> "dataset_name": [
> "java"
> ],
> "dev_src": [
> "sample.code"
> ],
> "dev_src_files": [
> "../data/java/sample.code"
> ],
> "dev_src_tag": null,
> "dev_src_tag_files": [
> null
> ],
> "dev_tgt": null,
> "dev_tgt_files": [
> null
> ],
> "dropout": 0.2,
> "dropout_emb": 0.2,
> "dropout_rnn": 0.2,
> "early_stop": 5,
> "emsize": 300,
> "filter_size": 5,
> "fix_embeddings": true,
> "force_copy": false,
> "gamma": 0.0,
> "grad_clipping": 5.0,
> "ignore_when_blocking": [],
> "layer_wise_attn": false,
> "learning_rate": 0.001,
> "length_penalty": "none",
> "log_file": "../tmp/code2jdoc_beam.txt",
> "lr_decay": 0.99,
> "max_characters_per_token": 30,
> "max_examples": -1,
> "max_relative_pos": 0,
> "max_src_len": 150,
> "max_tgt_len": 50,
> "model_dir": "../tmp",
> "model_file": "../tmp/code2jdoc.mdl",
> "model_name": "code2jdoc",
> "model_type": "rnn",
> "momentum": 0,
> "n_best": 1,
> "n_characters": 260,
> "nfilters": 100,
> "nhid": 200,
> "nlayers": 2,
> "num_head": 8,
> "only_generate": true,
> "optimizer": "adam",
> "parallel": false,
> "pred_file": "../tmp/code2jdoc_beam.json",
> "random_seed": 1013,
> "reload_decoder_state": null,
> "replace_unk": true,
> "reuse_copy_attn": false,
> "review_attn": false,
> "rnn_type": "LSTM",
> "share_decoder_embeddings": false,
> "sort_by_len": true,
> "split_decoder": false,
> "src_pos_emb": true,
> "stepwise_penalty": false,
> "test_batch_size": 64,
> "tgt_pos_emb": true,
> "trans_drop": 0.2,
> "uncase": true,
> "use_all_enc_layers": false,
> "use_code_type": false,
> "use_neg_dist": true,
> "use_src_char": false,
> "use_src_word": true,
> "use_tgt_char": false,
> "use_tgt_word": true,
> "verbose": false,
> "warmup_epochs": 0,
> "warmup_steps": 10000,
> "weight_decay": 0
> } ]
> 0%| | 0/2 [00:00<?, ?it/s]
> 
> Traceback (most recent call last):
> File "../main/test.py", line 474, in
> main(args)
> 
> File "../main/test.py", line 436, in main
> validate_official(args, dev_loader, model)
> 
> File "../main/test.py", line 278, in validate_official
> batch_inputs = prepare_batch(ex, model)
> 
> File "../main/test.py", line 216, in prepare_batch
> source_map = make_src_map(batch['src_map'])
> 
> File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/utils/copy_utils.py", line 34, in make_src_map
> 
> src_vocab_size = max([t.max() for t in data]) + 1
> File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/utils/copy_utils.py", line 34, in
> 
> src_vocab_size = max([t.max() for t in data]) + 1
> RuntimeError: operation does not have an identity.
> 
> 0%| | 0/2 [00:00<?, ?it/s]`
> Can you please tell how can I resolve this?
> Also, can you please tell how to run the tokenizer files, as there are 3 different files which you have uploaded, and none of them takes any input. It will be really helpful, sir.

On printing some lines for this error 
`tensor([2, 3])
2
tensor(3)
tensor([2, 3])
2
tensor(3)
tensor([], dtype=torch.int64)
0
Traceback (most recent call last):
  File "../main/test.py", line 474, in <module>
    main(args)
  File "../main/test.py", line 436, in main
    validate_official(args, dev_loader, model)
  File "../main/test.py", line 278, in validate_official
    batch_inputs = prepare_batch(ex, model)
  File "../main/test.py", line 216, in prepare_batch
    source_map = make_src_map(batch['src_map'])
  File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/utils/copy_utils.py", line 38, in make_src_map
    print(i.max())`

There are empty tensors coming.

To solve this error i tried passing 0 as max after which i got
`Traceback (most recent call last):
  File "../main/test.py", line 474, in <module>
    main(args)
  File "../main/test.py", line 436, in main
    validate_official(args, dev_loader, model)
  File "../main/test.py", line 285, in validate_official
    ex['src_vocab'])
  File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/translator/translation.py", line 61, in from_batch
    for n in range(self.n_best)]
  File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/translator/translation.py", line 61, in <listcomp>
    for n in range(self.n_best)]
  File "/Users/agbbps/Desktop/Internship/NeuralCodeSum-Latest/c2nl/translator/translation.py", line 45, in _build_target_tokens
    _, max_index = attn[i].max(0)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity`

**Comment by anshul17024** [comment]
Thank you so much sir. The generate.sh is working smoothly. Can you please tell how to use the tokenizer files, as there are 3 such files and no description is there about them. Also, there is no input asked in the tokenized files, so can you please tell the steps how to use them to generate the subtoken files. It will be really helpful.

**Comment by wasiahmad** [comment]
The tokenizers are pretty simple and straight-forward. You can instantiate those tokenizer classes to tokenize source codes for CamelCase and snake_case bases sub-tokenization. 

The preprocessing of the source code should be done as per prior works (as mentioned in the paper). We used preprocessed code in our experiments, we didn't preprocess by ourselves. Only the sub-tokenization is done by us and we provide the tokenizer for that. 

Please give some effort to understand the codebase. It will save both of our time which is precious.

**Comment by Guardian99** [comment]
The repository of TLCodeSum by Xing-Hu does not give any explanation for the preprocessing part @wasiahmad . There are open as well as closed issues for the same without any answers for the query raised.

**Comment by wasiahmad** [comment]
From section 4.1 of the [paper](https://xin-xia.github.io/publication/ijcai18.pdf):

> We use Eclipse’s JDT compiler to parse source code into AST trees. Then we extract the Java methods, the API sequences within these methods, and the corresponding Javadoc comments which are standard comments for Java methods. These comments that describe the functionalities of Java methods are taken as code summaries. The source code is tokenized into tokens before they are fed into the network. To decrease noise introduced to the learning process, we only take the first sentence of the comments since they typically describe the functionalities of Java methods according to Javadoc guidance. However, not every comment is useful, so some heuristic rules are required to filter the data. Methods with empty or just one-word descriptions are filtered out in this work. The setter, getter, constructor, test methods, and override methods, whose comments are easy to predict, are also excluded.

You can get the tokenized source code from AST. 

A simpler alternative is to consider white-space based tokenization for source code.

**Comment by anshul17024** [comment]
Thank you sir. Your responses were very useful!  :)

**Comment by Guardian99** [comment]
Thank you for being so active in answering the queries.
