### ISSUE TITLE
No such file: ../../data/java/test/code.original_subtoken while training a model

### ISSUE THREAD

**Issue by lyriccoder** [wasiahmad/NeuralCodeSum#30]
When I try to train a model by `bash transformer.sh 0,1 code2jdoc`, I get the error:
```
============TRAINING============
Traceback (most recent call last):
  File "../../main/train.py", line 675, in <module>
    set_defaults(args)
  File "../../main/train.py", line 153, in set_defaults
    raise IOError('No such file: %s' % train_src)
OSError: No such file: ../../data/java/train/code.original_subtoken
============TESTING============
Traceback (most recent call last):
  File "../../main/train.py", line 675, in <module>
    set_defaults(args)
  File "../../main/train.py", line 186, in set_defaults
    raise IOError('No such file: %s' % dev_src)
OSError: No such file: ../../data/java/test/code.original_subtoken
============Beam Search TESTING============
Traceback (most recent call last):
  File "../../main/test.py", line 448, in <module>
    set_defaults(args)
  File "../../main/test.py", line 151, in set_defaults
    raise IOError('No such file: %s' % dev_src)
OSError: No such file: ../../data/java/test/code.original_subtoken
```
So, I did the following steps (which are written in README):

```
git clone https://github.com/wasiahmad/NeuralCodeSum.git
cd NeuralCodeSum; pip install -r requirements.txt; python setup.py develop
```
```
cd  scripts/DATASET_NAME
```
```
bash transformer.sh 0,1 code2jdoc
```

Could you please tell me why do I get the error? Seems I need a dataset to train it, but there is no dataset in that folder.
I also downloaded `java_with_sbt.zip` and `java.zip` (which were provided by you in google drive), but there was no such file (java/test/code.original_subtoken)

**Comment by wasiahmad** [comment]
- Use `data/java/get_data.sh` scripts to download the dataset in Java. Do similarly for python. 

- I can see `code.original_subtoken` file in `java/test` directory.

![Screen Shot 2021-09-02 at 12 19 34 PM](https://user-images.githubusercontent.com/17520413/131888665-8ae7e98f-3a50-40a8-81fb-2c4e22ee2ed6.png)

**Comment by lyriccoder** [comment]
@wasiahmad  Why did u close the issue? The problem is not solved

1) Problem is in your script get_data.sh, it doesn't download correct java archive. It's size is 1 KB.
2) Could you please provide a pretrained model? Some documentation is absent and people have to solve problems manually (fixing python scripts) or running some bash scripts, renaming fles, etc.
If you provided a pretrained model, it would be easier to obtain the results in your paper.

Could you please provide a full archive with pretrained model (and all needed files)?

**Comment by wasiahmad** [comment]
All the codes are tested, so I do not know why you are complaining about get_data.sh. If it doesn't download the data in your machine, it does not mean the script is wrong. It works fine on my machine.

We no longer provide any support for this project. That's why I closed the issue.
