### ISSUE TITLE
Questions about javadoc generation

### ISSUE THREAD

**Issue by wangyu1997** [wasiahmad/NeuralCodeSum#31]
Hello, could you please share your scripts about pre-processing the java comment? I  tried to do that myself but it seems that the sentence looks different from yours.

**Comment by wasiahmad** [comment]
I would encourage you to use Java Language processor implemented [here](https://github.com/facebookresearch/CodeGen/blob/main/codegen_sources/preprocessing/lang_processors/tree_sitter_processor.py#L59) using Tree Sitter. You can modify the code to get different types of comments (`{"comment", "line_comment", "block_comment"}`).
