### ISSUE TITLE
Model is not learning and is not generating meaningful output

### ISSUE THREAD

**Issue by yijungan** [wasiahmad/NeuralCodeSum#38]
Hi Wasi,

The paper is very insightful and I want to say thank you for the effort and the finding, first and foremost!

I have tested the code in two env: python 3.9 + Pytorch 1.11 and python 3.7 + Pytorch 1.5.0 and I didn't make any changes other than using the method mentioned in this [thread ](https://github.com/wasiahmad/NeuralCodeSum/issues/26#issuecomment-870528912)to resolve error (`RuntimeError: "index_select_out_cuda_impl" not implemented for 'Float While comment generation testing the code`) during testing.

the suggested changes that I made:
>  (beam.py line:131 prevK = bestScoresId / numWords). You can modify this line to prevK = bestScoresId // numWords

### Model not learning during training process:
I have tried to reproduce the transformer with copy attention result from the paper with the provided dataset, however, both training processes did not give meaningful result:

For python 3.9 + Pytorch 1.11
snippet of the training process looks like:

> 01/13/2023 06:47:30 PM: [ dev valid official: Epoch = 70 | bleu = 2.30 | rouge_l = 3.62 | Precision = 2.52 | Recall = 7.44 | F1 = 3.33 | examples = 8714 | valid time = 164.42 (s) ]
01/13/2023 06:52:14 PM: [ train: Epoch 71 | perplexity = 404.95 | ml_loss = 105.54 | Time for epoch = 283.49 (s) ]
01/13/2023 06:54:59 PM: [ dev valid official: Epoch = 71 | bleu = 2.30 | rouge_l = 3.62 | Precision = 2.52 | Recall = 7.44 | F1 = 3.33 | examples = 8714 | valid time = 164.19 (s) ]

The above is the last epoch, and the scores from the metric are not quite far from the scores from **epoch 1 below**, while ml_loss do not have significant drop:

> 01/13/2023 10:32:20 AM: [ train: Epoch 1 | perplexity = 12872.61 | ml_loss = 164.32 | Time for epoch = 258.82 (s) ]
01/13/2023 10:35:09 AM: [ dev valid official: Epoch = 1 | bleu = 2.05 | rouge_l = 0.86 | Precision = 0.58 | Recall = 1.92 | F1 = 0.79 | examples = 8714 | valid time = 167.51 (s) ]
01/13/2023 10:35:09 AM: [ Best valid: bleu = 2.05 (epoch 1, 2179 updates) ]

And for python 3.7 + Pytorch 1.5.0
the ml loss and perplexity are both nan and net_loss is containing nan for both ml_loss and perplexity for all of the epochs.

While the trained logs from the previous [thread](https://github.com/wasiahmad/NeuralCodeSum/issues/5#issuecomment-649125577), which has a close result to the paper's, look something like this:
first epoch:

> 06/12/2020 03:56:03 PM: [ train: Epoch 1 | perplexity = 22026.47 | ml_loss = 452.92 | Time for epoch = 406.76 (s) ]
06/12/2020 03:58:45 PM: [ dev valid official: Epoch = 1 | bleu = 3.31 | rouge_l = 5.53 | Precision = 4.84 | Recall = 11.51 | F1 = 5.52 | examples = 8714 | valid time = 158.37 (s) ]

last epoch:

> 06/20/2020 08:02:14 AM: [ train: Epoch 122 | perplexity = 2.17 | ml_loss = 15.94 | Time for epoch = 1169.03 (s) ]
06/20/2020 08:08:00 AM: [ dev valid official: Epoch = 122 | bleu = 40.50 | rouge_l = 51.66 | Precision = 58.31 | Recall = 54.11 | F1 = 53.57 | examples = 8714 | valid time = 342.41 (s) ]

### Saved model does not output meaningful result
Last but not least, I have also tried to use trained model provided by from the previous [thread](https://github.com/wasiahmad/NeuralCodeSum/issues/5#issuecomment-649125577)
 and generate.sh to generate prediction of the sample.code
However, the result looks something like this:

>   "0": [
>         "( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ("
>     ],
>     "1": [
>         ", , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,"
>     ],

My guess is there might be bug in the decoder base that causing this issue? Because both the trained transformer and trained rnn suffer the same issue when I run the generate.sh file. 

Any hint on what might be the problem and where to look to resolve this issue?

Many thanks in advance!

**Comment by wasiahmad** [comment]
We no longer support the codebase. When we released the code, we verified it.
