### ISSUE TITLE
Upload Pre-Trained model weights

### ISSUE THREAD

**Issue by nik-suri** [wasiahmad/NeuralCodeSum#5]
Hi, would it be possible to upload the models which you trained for the paper you published? I would like to test the code summary generation without having to train a model from scratch, which is quite time and resource intensive.

**Comment by wasiahmad** [comment]
We didn't store the saved weights, however, we can train the model again to share the weight files. We may do it by next week. Thank you.

**Comment by nik-suri** [comment]
That would be very helpful - thank you!

**Comment by srvvrma** [comment]
@nik-suri Please text me your email id l.I'll share a trained model with you.

**Comment by srvvrma** [comment]
Trained Model:
https://drive.google.com/drive/folders/1Efy4sn530mrveCjyHSyknkis8OOV0uh9?usp=sharing

code2jdoc.mdl -> transformer
code2jdoc_rnn.mdl -> rnn

**Comment by ksrinivs64** [comment]
This looks like it was created for Java.  I was interested in building the Python models.
