### ISSUE TITLE
Summary produced in Spanish instead of English

### ISSUE THREAD

**Issue by anshul17024** [wasiahmad/NeuralCodeSum#7]
Hi, I have a 20,000 line JAVA code, with all variable/method naming conventions used, in English. Yet, some of the method summary produced are coming out to be in Spanish, which I don't know why? For example: 

`validateAssetSerialNumber :::: persists a contentelement el contenido , serialize ldap`
`isAllAssetSerialNumberValid :::: metodo que contenido de serialize`
`setStausCompleteForAutoRcuRef :::: metodo donates work of information_schema el violation`

Can someone please give some idea why this might be happening?

**Comment by wasiahmad** [comment]
What do you mean by `20,000 line JAVA code`? Did you train the model on your own data?
