### ISSUE TITLE
Script to generate code.subtoken file

### ISSUE THREAD

**Issue by ghost** [wasiahmad/NeuralCodeSum#9]
What are the preprocessing steps carried out by you ? Could you please provide the script to convert code.original to code.original_subtoken ?

**Comment by wasiahmad** [comment]
Would you mind reading our paper to learn about the preprocessing steps? We do not have the exact preprocessing script but we have this (https://gist.github.com/saikat107/b4c71e6cd8316d81ee6d10932c7ea4d4) which we use in our work.
